VERSION="1.0.0"

[[PRINCIPALS]]
name="Tokens Issuer"

[[CURRENCIES]]
code="XRP"
issuer="GBS5D3MWYMKVFVDWPHZGD2MR5VLTFBL4P5LEPW6KJQ2GMIOBZ2FML5FO"
name="XRP"
desc="XRP Token"
image="https://cryptologos.cc/logos/xrp-xrp-logo.png"

[[CURRENCIES]]
code="XLM"
issuer="GAQBK7HDP7TYFXUGZDGXCCUTKXJ6WJ3OJZBIGDRERWFDH4AVUCSPAJ3O"
name="XLM"
desc="Stellar Lumens"
image="https://cryptologos.cc/logos/stellar-xlm-logo.png"

[[CURRENCIES]]
code="BNB"
issuer="GAQBK7HDP7TYFXUGZDGXCCUTKXJ6WJ3OJZBIGDRERWFDH4AVUCSPAJ3O"
name="BNB"
desc="BNB Token"
image="https://cryptologos.cc/logos/bnb-bnb-logo.png"

[[CURRENCIES]]
code="SOL"
issuer="GAQBK7HDP7TYFXUGZDGXCCUTKXJ6WJ3OJZBIGDRERWFDH4AVUCSPAJ3O"
name="SOL"
desc="Solana Token"
image="https://cryptologos.cc/logos/solana-sol-logo.png"

[[CURRENCIES]]
code="ETH"
issuer="GAQBK7HDP7TYFXUGZDGXCCUTKXJ6WJ3OJZBIGDRERWFDH4AVUCSPAJ3O"
name="ETH"
desc="Ethereum Token"
image="https://cryptologos.cc/logos/ethereum-eth-logo.png"

[[CURRENCIES]]
code="DOGE"
issuer="GAQBK7HDP7TYFXUGZDGXCCUTKXJ6WJ3OJZBIGDRERWFDH4AVUCSPAJ3O"
name="DOGE"
desc="Dogecoin"
image="https://cryptologos.cc/logos/dogecoin-doge-logo.png"